### PR TITLE
Create alternative authentications

### PR DESCRIPTION
**Pull request by zenithyap**
Added authentication for Facebook, Github and Twitter

### CODE REVIEW

**Comment by Acerizm** [comment]
LGTM for signing in with Github! Would like to have @Kang-Quan to review for Facebook and Twitter as I do not have any Facebook and Twitter accounts.

**Review by Kang-Quan — CHANGES_REQUESTED** [review]
Tested auth for all 3 facebook, github and twitter (X).

Able to sign into github and twitter. But unable to sign in using facebook.
image

It could be due to the domain of this URL isn't included in the app's domains

**Comment by Kang-Quan** [comment]
Checked documentations for facebook. It requires my account to be a developer account. After signing up, it throws a different error, account-exists-with-different-credential. This is because i have created an email with password account that has the same email as facebook. After deleting that account i am able to log into facebook.

**Review by Kang-Quan — APPROVED** [review]
Changed the settings on firebase to allow for multiple email. Users can now have multiple accounts (not linked), eg email + pw, SSO with the same email address. LGTM.

**Comment by Acerizm** [comment]
@Kang-Quan Thank you for checking thouroughly!

**Pull request merged**
