### PR TITLE
Separate dev and prod for k8 and non-k8

### PR DESCRIPTION
**Pull request by Acerizm**
Summary:

1. Docker compose file is moved to `Server-Configs` where there are 2 folders `With-K8` and `Without-K8`.
2. In `Without-K8`, docker compose for dev environment is in `dev` folder and another docker compose file for current live server is in `prod` folder
3. Front-end will automatically switch routes based on env variable given in the respective dockerfile
4. Front-end will have 2 docker files for development and production ( Dockerfile.prod will be used in github actions )

### CODE REVIEW

**Comment by huizhuansam** [comment]
Takes about 10 minutes for a clean build

Screenshot 2023-11-11 at 12 11 43 AM

Frontend service still fails to build on my laptop even after re-cloning the project. I guess there is just something wrong with my system. Will continue to use `npm start`.

Other containers are up and healthy.
Screenshot 2023-11-11 at 12 14 16 AM

Images are just under 3GB.
Screenshot 2023-11-11 at 12 15 56 AM

System: 
* 2020 Intel i7 Macbook Air, 16GB, macOS 14.1
* Docker v4.25.0

**Comment by huizhuansam** [comment]
LGTM, reminder to update the root README

**Review by huizhuansam — APPROVED** [review]
LGTM, reminder to update the root README

**Review by zenithyap — APPROVED** [review]
Everything seems to be working fine, thanks a lot for setting up the dev! :D

**Pull request merged**
